version: "3.7"
services:
  webapp:
    build: ./webapp
    image: open-city-toolkit/webapp
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: grass
        target: /oct/grass
      - type: volume
        source: output
        target: /oct/output
      - type: volume
        source: geoserver_data
        target: /usr/share/geoserver/data_dir
  geoserver:
    build: ./geoserver
    image: open-city-toolkit/geoserver
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: geoserver_data
        target: /usr/share/geoserver/data_dir
volumes:
  geoserver_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./geoserver_data_dir
  grass:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./grass
  output:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./output
